# Generated by Django 5.0.1 on 2024-01-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobileNumber',
            field=models.DecimalField(decimal_places=0, default=9502520845, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('primary check', 'primary check'), ('consultation', 'consultation'), ('admitted', 'admitted'), ('discharged', 'discharged')], default='consultation', max_length=20),
        ),
        migrations.CreateModel(
            name='visited_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_datetime', models.DateTimeField(auto_now=True)),
                ('mobileNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='visited_dates',
        ),
    ]
