# Generated by Django 5.0.1 on 2024-01-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(choices=[('cardi', 'Cardiology'), ('gastro', 'Gastroenterology'), ('pyschi', 'Psychiatry'), ('hameo', 'Haematology'), ('cc', 'Critical Care'), ('surg', 'Surgeon')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('department', models.ManyToManyField(to='hospital.department')),
            ],
        ),
    ]
